version: '3.8'

services:
  nextjs:
    build: .
    container_name: nextjs
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
    # command: sh -c "npm run build && npx typeorm migration:run -d ./dist/data-source.js && npm run start:dev"
